apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.ratingService.port }}
      targetPort: {{ .Values.service.ratingService.targetPort }}
  type: {{ .Values.service.ratingService.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: rating-service-mongodb
spec:
  selector:
    app: rating-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.ratingServiceMongo.port }}
      targetPort: {{ .Values.service.ratingServiceMongo.targetPort }}
  type: {{ .Values.service.ratingServiceMongo.type }}
