apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceRegistry.port }}
      targetPort: {{ .Values.service.serviceRegistry.targetPort }}
  type: {{ .Values.service.serviceRegistry.type }}
